services:
  - type: web
    name: trackshopee-admin
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: APP_USERNAME
        value: hieunguyen01
      - key: APP_PASSWORD
        sync: false
      - key: OTISTX_API_KEY
        sync: false
