const API_BASE='';
const REQUEST_TIMEOUT_MS=20000;
const state={activeToast:null,activeToastTimer:null,activeTab:'voucher',vouchers:[],freeships:[],voucherMap:new Map(),savingAll:false,savingId:'',currentSpcSt:'',currentSpcF:'',loginSourceRaw:'',qrSessionId:'',qrPollTimer:null,linkOpen:false,cookieOpen:true,batchAccounts:[]};
const els={toastContainer:document.getElementById('toast-container'),cookieToggle:document.getElementById('voucher-cookie-toggle'),cookiePanel:document.getElementById('voucher-cookie-panel'),cookieInput:document.getElementById('voucher-cookie-input'),saveFixedButton:document.getElementById('voucher-save-fixed-btn'),refreshButton:document.getElementById('voucher-refresh-btn'),actionStatus:document.getElementById('voucher-action-status'),linkToggle:document.getElementById('voucher-link-toggle'),linkPanel:document.getElementById('voucher-link-panel'),linkInput:document.getElementById('voucher-link-input'),linkSubmitButton:document.getElementById('voucher-link-submit-btn'),linkStatus:document.getElementById('voucher-link-status'),tabVoucher:document.getElementById('voucher-tab-voucher'),tabFreeship:document.getElementById('voucher-tab-freeship'),countVoucher:document.getElementById('voucher-count-badge'),countFreeship:document.getElementById('voucher-freeship-count-badge'),list:document.getElementById('voucher-list'),loginInput:document.getElementById('voucher-login-input'),loginButton:document.getElementById('voucher-login-btn'),qrButton:document.getElementById('voucher-qr-btn'),qrCancelButton:document.getElementById('voucher-qr-cancel-btn'),qrBox:document.getElementById('voucher-qr-box'),qrImage:document.getElementById('voucher-qr-image'),qrStatus:document.getElementById('voucher-qr-status'),cookieValue:document.getElementById('voucher-cookie-value'),copyCookieButton:document.getElementById('voucher-copy-cookie-btn'),copySpcFButton:document.getElementById('voucher-copy-spcf-btn'),updateSpcStButton:document.getElementById('voucher-update-spcst-btn'),batchSummary:document.getElementById('voucher-batch-summary')};
function clearToast(force=false){if(!state.activeToast)return;if(state.activeToastTimer){clearTimeout(state.activeToastTimer);state.activeToastTimer=null;}const t=state.activeToast;state.activeToast=null;if(force){t.remove();return;}t.classList.remove('is-visible');setTimeout(()=>t.remove(),180)}
function showToast(message,type='info',duration=2600){if(!els.toastContainer||!message)return;clearToast(true);const t=document.createElement('div');t.className='toast toast-'+type;t.textContent=message;els.toastContainer.appendChild(t);state.activeToast=t;requestAnimationFrame(()=>t.classList.add('is-visible'));state.activeToastTimer=setTimeout(()=>clearToast(),duration)}
const showError=(m)=>showToast(m,'error',3200),showSuccess=(m)=>showToast(m,'success',2200),showProgress=(m)=>showToast(m,'progress',1800);
function setInlineStatus(node,message,type){if(!node)return;if(!message){node.classList.add('hidden');node.textContent='';node.dataset.type='';return;}node.classList.remove('hidden');node.textContent=message;node.dataset.type=type||'progress';}
function setButtonBusy(button,busy,busyLabel){if(!button)return;if(!button.dataset.defaultLabel)button.dataset.defaultLabel=button.textContent;button.disabled=busy;button.textContent=busy?busyLabel:button.dataset.defaultLabel;}
function escapeHtml(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function normalizeCookieInput(v){const raw=String(v||'').trim();if(!raw)return'';const m=raw.match(/SPC_ST=[^;|\s"]+/);if(m)return m[0];if(!/=/.test(raw))return'SPC_ST='+raw;return raw;}
function extractSpcSt(raw){const s=String(raw||'').trim();const m=s.match(/SPC_ST=([^;|\s"]+)/);return m?m[1]:s;}
function extractSpcF(raw){const s=String(raw||'').trim();const m=s.match(/SPC_F=[^;|\s"]+/);return m?m[0]:'';}
function parseCookieLines(v){return String(v||'').split(/\r?\n/).map(normalizeCookieInput).filter((x)=>x.length>=10)}
function parseLoginLines(v){return String(v||'').split(/\r?\n/).map((x)=>String(x||'').trim()).filter(Boolean)}
function getBatchCookies(){return state.batchAccounts.filter((x)=>x.ok&&x.spcSt).map((x)=>'SPC_ST='+x.spcSt)}
function getCookieList(){return parseCookieLines(els.cookieInput?els.cookieInput.value:'')}
function syncSpcDisplay(){if(!els.cookieValue)return;const payload=getBatchCookies().length?getBatchCookies().join('\n'):(state.currentSpcSt?('SPC_ST='+state.currentSpcSt):'Chưa có SPC_ST.');els.cookieValue.value=payload;}
function ensureCurrentCookieInInput(){if(!els.cookieInput)return;const cookies=getCookieList();if(cookies.length)return;const batch=getBatchCookies();if(batch.length){els.cookieInput.value=batch.join('\n');return;}if(state.currentSpcSt)els.cookieInput.value='SPC_ST='+state.currentSpcSt;}
function setCurrentSpcData(cookie,fallback,input){const spcSt=extractSpcSt(cookie||fallback||'');state.currentSpcSt=spcSt||'';state.currentSpcF=extractSpcF(input||'');state.loginSourceRaw=String(input||'').trim();state.batchAccounts=spcSt?[{ok:true,source:state.loginSourceRaw||'SPC_ST',spcSt,spcF:state.currentSpcF,message:''}]:[];syncSpcDisplay();ensureCurrentCookieInInput();setInlineStatus(els.batchSummary,spcSt?'Đã cập nhật SPC_ST hiện tại.':'',spcSt?'success':'');}
async function fetchJson(url,options={}){const controller=new AbortController();const timeoutId=setTimeout(()=>controller.abort(),options.timeoutMs||REQUEST_TIMEOUT_MS);let response;try{response=await fetch(url,{method:options.method||'GET',headers:{'Content-Type':'application/json',...(options.headers||{})},body:options.body?JSON.stringify(options.body):undefined,signal:controller.signal});}catch(error){if(error&&error.name==='AbortError')throw new Error('API phản hồi quá lâu, đã tự dừng sau 20 giây.');throw error;}finally{clearTimeout(timeoutId);}const text=await response.text();let data;try{data=text?JSON.parse(text):null;}catch{data=text;}if(response.status===401){window.location.href='/login.html?next=/voucher.html';throw new Error('Phiên đăng nhập đã hết hạn.');}return{ok:response.ok,status:response.status,data,text};}
async function apiRequest(path,options={}){const result=await fetchJson(API_BASE+path,options);const payload=result&&typeof result.data==='object'&&result.data!==null?result.data:{};if(!result.ok||payload.error)throw new Error(payload.error||payload.message||('HTTP '+result.status));return payload;}
async function autopeeApi(path,options={}){return fetchJson(API_BASE+'/autopee-api'+path,options)}
function extractVoucherList(payload){if(Array.isArray(payload))return payload;if(payload&&Array.isArray(payload.data))return payload.data;if(payload&&payload.data&&Array.isArray(payload.data.data))return payload.data.data;if(payload&&payload.data&&payload.data.data&&Array.isArray(payload.data.data.items))return payload.data.data.items;if(payload&&payload.data&&Array.isArray(payload.data.items))return payload.data.items;return[];}
function normalizeVoucherItem(item,source){return{source,promotionId:item.promotionId||item.promotionid,voucherCode:item.voucherCode||item.voucher_code,signature:item.signature,voucherName:item.voucherName||item.voucher_name||item.title||item.voucherCode||item.voucher_code||source,description:item.description||'',discountValue:Number(item.discountValue||item.discount_value||0),discountPercentage:Number(item.discountPercentage||item.discount_percentage||0),discountCap:Number(item.discountCap||item.discount_cap||0),minSpend:Number(item.minSpend||item.min_spend||0),endTime:Number(item.endTime||item.end_time||0),validDays:Number(item.validDays||item.valid_days||0),customisedLabels:Array.isArray(item.customisedLabels)?item.customisedLabels:Array.isArray(item.customised_labels)?item.customised_labels:[]};}
function formatCompactMoney(v){const n=Number(v||0);if(!n)return'0₫';return Math.floor(n/100000).toLocaleString('vi-VN')+'.000 đ';}
function formatDateTime(unix){if(!unix)return'';return new Date(unix*1000).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});}
function getExpiryText(item){if(item.validDays>0)return item.validDays+' ngày kể từ khi nhận';if(item.endTime>0)return formatDateTime(item.endTime);return'';}
function parseSaveResult(result,voucherCode){const payload=result&&typeof result.data==='object'&&result.data!==null?result.data:result;const inner=payload&&typeof payload.data==='object'&&payload.data!==null?payload.data:payload;const voucherInfo=inner&&inner.data&&inner.data.voucher?inner.data.voucher:inner&&inner.voucher?inner.voucher:null;const errorCode=inner&&typeof inner.error==='number'?inner.error:payload&&typeof payload.error==='number'?payload.error:null;const claimedBefore=Boolean(voucherInfo&&voucherInfo.is_claimed_before===true);if(errorCode===0)return{ok:true,message:'Đã lưu voucher '+voucherCode+' thành công.'};if(errorCode===5||claimedBefore)return{ok:true,message:'Voucher '+voucherCode+' đã được lưu trước đó.',claimedBefore:true};return{ok:false,message:(inner&&inner.error_msg)||(payload&&payload.error)||(payload&&payload.message)||'API chưa xác nhận đã lưu voucher.'};}
function updateTabCounts(){if(els.countVoucher)els.countVoucher.textContent=String(state.vouchers.length);if(els.countFreeship)els.countFreeship.textContent=String(state.freeships.length);}
function renderCatalog(){if(!els.list)return;const items=state.activeTab==='voucher'?state.vouchers:state.freeships;if(!items.length){els.list.innerHTML='<div class="voucher-empty-card">Chưa có voucher nào.</div>';return;}els.list.innerHTML=items.map((item)=>{const typeClass=item.source==='freeship'?'is-freeship':'is-voucher';const discountPrimary=item.source==='freeship'?(item.discountValue>0?('Tối đa '+formatCompactMoney(item.discountValue)):'Miễn phí vận chuyển'):(item.discountPercentage>0?('Giảm '+item.discountPercentage+'%'+(item.discountCap>0?(' · tối đa '+formatCompactMoney(item.discountCap)):'')):('Giảm '+formatCompactMoney(item.discountValue)));const minSpend=item.minSpend>0?('Đơn tối thiểu '+formatCompactMoney(item.minSpend)):'';const expiry=getExpiryText(item);const disabled=!getCookieList().length&&!getBatchCookies().length&&!state.currentSpcSt;const buttonText=state.savingId===String(item.promotionId)?'Đang lưu…':'Lưu vào tài khoản';const labels=(item.customisedLabels||[]).filter(Boolean).slice(0,2).map((label)=>'<span class="voucher-mini-tag">'+escapeHtml(label)+'</span>').join('');return'<article class="voucher-catalog-card '+typeClass+'"><div class="voucher-card-topline"></div><div class="voucher-card-body"><div class="voucher-card-head"><div class="voucher-card-icon">'+(item.source==='freeship'?'🚚':'🎁')+'</div><div class="voucher-card-meta"><div class="voucher-card-code">'+escapeHtml(item.voucherCode||'-')+'</div><div class="voucher-card-name">'+escapeHtml(item.voucherName||item.voucherCode||'-')+'</div></div></div><div class="voucher-card-price">'+escapeHtml(discountPrimary)+'</div><div class="voucher-card-info">'+(minSpend?'<div>• '+escapeHtml(minSpend)+'</div>':'')+(expiry?'<div>• HSD: '+escapeHtml(expiry)+'</div>':'')+(labels?'<div class="voucher-card-tags">'+labels+'</div>':'')+'</div><div class="voucher-card-actions"><button class="voucher-copy-btn" type="button" data-copy-code="'+escapeHtml(item.voucherCode||'')+'">Copy mã</button><button class="voucher-save-btn" type="button" data-save-code="'+escapeHtml(item.voucherCode||'')+'" '+(disabled?'disabled':'')+'>'+escapeHtml(buttonText)+'</button></div>'+(item.description?'<button class="voucher-detail-toggle" type="button" data-detail-toggle="'+escapeHtml(item.voucherCode||'')+'">Điều kiện sử dụng</button><div class="voucher-description hidden" data-detail-box="'+escapeHtml(item.voucherCode||'')+'">'+escapeHtml(item.description)+'</div>':'')+'</div></article>';}).join('');}
function syncTabUi(){if(els.tabVoucher)els.tabVoucher.classList.toggle('is-active',state.activeTab==='voucher');if(els.tabFreeship)els.tabFreeship.classList.toggle('is-active',state.activeTab==='freeship');renderCatalog();}
async function loadVoucherCatalog(){setButtonBusy(els.refreshButton,true,'Đang tải...');setInlineStatus(els.actionStatus,'Đang tải danh sách voucher từ Autopee...','progress');try{const[voucherResult,freeshipResult]=await Promise.all([autopeeApi('/api/shopee/vouchers?limit=200'),autopeeApi('/api/shopee/freeships?limit=200')]);state.vouchers=extractVoucherList(voucherResult.data).map((item)=>normalizeVoucherItem(item,'voucher'));state.freeships=extractVoucherList(freeshipResult.data).map((item)=>normalizeVoucherItem(item,'freeship'));state.voucherMap.clear();state.vouchers.concat(state.freeships).forEach((item)=>{if(item.voucherCode&&item.promotionId&&item.signature)state.voucherMap.set(String(item.voucherCode).trim().toUpperCase(),item);});updateTabCounts();syncTabUi();setInlineStatus(els.actionStatus,'Đã tải '+state.vouchers.length+' voucher và '+state.freeships.length+' freeship.','success');}catch(error){setInlineStatus(els.actionStatus,error.message||'Không tải được danh sách voucher.','error');showError(error.message||'Không tải được danh sách voucher.');if(els.list)els.list.innerHTML='<div class="voucher-empty-card">Không tải được danh sách voucher.</div>';}finally{setButtonBusy(els.refreshButton,false,'Đang tải...');}}
async function saveVoucherWithCookies(voucher){const directCookies=getCookieList();const queue=directCookies.length?directCookies:(getBatchCookies().length?getBatchCookies():(state.currentSpcSt?['SPC_ST='+state.currentSpcSt]:[]));if(!queue.length)throw new Error('Bạn chưa dán cookie Shopee hoặc SPC_ST.');let lastError='';for(const cookie of queue){const result=await autopeeApi('/api/shopee/save-voucher',{method:'POST',body:{cookie,voucher_promotionid:voucher.promotionId,signature:voucher.signature,voucher_code:voucher.voucherCode}});if(!result.ok){lastError=typeof result.data==='object'&&result.data!==null?(result.data.error||result.data.message||('HTTP '+result.status)):('HTTP '+result.status);continue;}const parsed=parseSaveResult(result,voucher.voucherCode);if(parsed.ok)return parsed;lastError=parsed.message;}throw new Error(lastError||('Không thể lưu voucher '+voucher.voucherCode));}
async function saveVoucherByCode(code,label){const voucher=state.voucherMap.get(String(code||'').trim().toUpperCase());if(!voucher){showError('Chưa có metadata cho mã '+label+'.');return;}state.savingId=String(voucher.promotionId);renderCatalog();setInlineStatus(els.actionStatus,'Đang lưu '+voucher.voucherCode+'...','progress');showProgress('Đang lưu '+label+'...');try{const parsed=await saveVoucherWithCookies(voucher);setInlineStatus(els.actionStatus,parsed.message,parsed.claimedBefore?'progress':'success');showSuccess(parsed.message);}catch(error){setInlineStatus(els.actionStatus,error.message||'Lưu voucher thất bại.','error');showError(error.message||'Lưu voucher thất bại.');}finally{state.savingId='';renderCatalog();}}
async function saveEveryVisibleVoucher(){const items=state.vouchers.concat(state.freeships);if(!items.length){showError('Chưa có voucher để lưu.');return;}state.savingAll=true;setButtonBusy(els.saveFixedButton,true,'Đang lưu...');setInlineStatus(els.actionStatus,'Đang lưu toàn bộ voucher đang hiển thị...','progress');let successCount=0,claimedCount=0,failedCount=0;for(const item of items){try{const parsed=await saveVoucherWithCookies(item);if(parsed.claimedBefore)claimedCount+=1;else successCount+=1;}catch{failedCount+=1;}}state.savingAll=false;setButtonBusy(els.saveFixedButton,false,'Đang lưu...');const summary='Đã lưu '+successCount+' voucher'+(claimedCount?(', '+claimedCount+' đã tồn tại'):'')+(failedCount?(', '+failedCount+' lỗi'):'');setInlineStatus(els.actionStatus,summary,failedCount?'error':'success');if(failedCount)showError(summary);else showSuccess(summary);}
async function submitVoucherLink(){const link=String(els.linkInput?els.linkInput.value:'').trim();if(!link){setInlineStatus(els.linkStatus,'Bạn chưa nhập link voucher.','error');showError('Bạn chưa nhập link voucher.');return;}setButtonBusy(els.linkSubmitButton,true,'Đang thêm...');setInlineStatus(els.linkStatus,'Đang gửi link voucher...','progress');try{const result=await autopeeApi('/api/shopee/submit-link',{method:'POST',body:{link}});if(!result.ok)throw new Error((result.data&&(result.data.error||result.data.message))||('HTTP '+result.status));const payload=result.data||{};const message=payload.message||payload.error||'Đã gửi link voucher.';setInlineStatus(els.linkStatus,message,payload.ok===false?'error':'success');if(payload.ok===false)showError(message);else showSuccess(message);if(payload.ok!==false&&els.linkInput){els.linkInput.value='';await loadVoucherCatalog();}}catch(error){setInlineStatus(els.linkStatus,error.message||'Không gửi được link voucher.','error');showError(error.message||'Không gửi được link voucher.');}finally{setButtonBusy(els.linkSubmitButton,false,'Đang thêm...');}}
async function loginByAccount(){const lines=parseLoginLines(els.loginInput?els.loginInput.value:'');if(!lines.length){showError('Bạn chưa nhập user|pass|SPC_F.');return;}setButtonBusy(els.loginButton,true,'Đang lấy...');setInlineStatus(els.batchSummary,'Đang xử lý '+lines.length+' tài khoản...','progress');showProgress('Đang lấy SPC_ST hàng loạt...');const results=[];let successCount=0;try{for(const input of lines){try{const data=await apiRequest('/api/login',{method:'POST',body:{input}});const cookie=data.cookie||data.spcST||'';if(!cookie)throw new Error('API không trả về SPC_ST.');results.push({ok:true,source:input,spcSt:extractSpcSt(cookie||data.spcST||''),spcF:extractSpcF(input),message:''});successCount+=1;}catch(error){results.push({ok:false,source:input,spcSt:'',spcF:extractSpcF(input),message:error.message||'Không thể lấy SPC_ST.'});}}state.batchAccounts=results;const successItems=results.filter((x)=>x.ok&&x.spcSt);if(successItems.length){const last=successItems[successItems.length-1];state.currentSpcSt=last.spcSt;state.currentSpcF=last.spcF||'';state.loginSourceRaw=last.source||'';syncSpcDisplay();ensureCurrentCookieInInput();}else{syncSpcDisplay();}if(successCount){const message='Đã lấy SPC_ST thành công cho '+successCount+'/'+lines.length+' tài khoản.';setInlineStatus(els.batchSummary,message,successCount===lines.length?'success':'error');showSuccess(message);}else{setInlineStatus(els.batchSummary,'Không lấy được SPC_ST cho tài khoản nào.','error');showError('Không lấy được SPC_ST cho tài khoản nào.');}}finally{setButtonBusy(els.loginButton,false,'Đang lấy...');}}
function stopQrPolling(){if(state.qrPollTimer){clearInterval(state.qrPollTimer);state.qrPollTimer=null;}}
function resetQrUi(){state.qrSessionId='';stopQrPolling();if(els.qrBox)els.qrBox.classList.add('hidden');if(els.qrCancelButton)els.qrCancelButton.classList.add('hidden');if(els.qrButton)els.qrButton.classList.remove('hidden');if(els.qrImage)els.qrImage.src='';if(els.qrStatus)els.qrStatus.textContent='Chờ quét QR...';setButtonBusy(els.qrButton,false,'Đang tạo...');}
async function startQrLogin(){setButtonBusy(els.qrButton,true,'Đang tạo...');showProgress('Đang tạo QR...');try{const data=await apiRequest('/api/qr/generate',{method:'POST',body:{}});state.qrSessionId=data.sessionId||'';if(!state.qrSessionId)throw new Error('API không trả về session QR.');if(els.qrImage)els.qrImage.src=String(data.qrBase64||'').startsWith('data:')?data.qrBase64:('data:image/png;base64,'+data.qrBase64);if(els.qrBox)els.qrBox.classList.remove('hidden');if(els.qrCancelButton)els.qrCancelButton.classList.remove('hidden');if(els.qrButton)els.qrButton.classList.add('hidden');if(els.qrStatus)els.qrStatus.textContent='Chờ quét QR...';stopQrPolling();state.qrPollTimer=setInterval(pollQrStatus,2000);}catch(error){resetQrUi();showError(error.message||'Không tạo được QR.');}}
async function pollQrStatus(){if(!state.qrSessionId)return;try{const data=await apiRequest('/api/qr/status/'+state.qrSessionId);if(data.status==='waiting'){if(els.qrStatus)els.qrStatus.textContent='Chờ quét QR...';return;}if(data.status==='scanned'){if(els.qrStatus)els.qrStatus.textContent='Đã quét, chờ xác nhận trên app...';return;}if(data.status==='success'||data.status==='done'){const cookie=data.cookie||data.spcST||'';if(!cookie)throw new Error('QR thành công nhưng không nhận được cookie.');setCurrentSpcData(cookie,data.spcST||'','QR Login');showSuccess('QR login thành công.');resetQrUi();return;}if(data.status==='failed'||data.status==='expired'||data.status==='error'){showError(data.error||'QR đã hết hạn.');resetQrUi();}}catch(error){showError(error.message||'Lỗi QR.');resetQrUi();}}
async function cancelQrLogin(){try{if(state.qrSessionId)await apiRequest('/api/qr/cancel',{method:'POST',body:{sessionId:state.qrSessionId}});}catch{}finally{resetQrUi();showSuccess('Đã hủy QR.');}}
async function copyCurrentSpcSt(){const payload=String(els.cookieValue?els.cookieValue.value:'').trim();if(!payload||payload==='Chưa có SPC_ST.'){showError('Chưa có SPC_ST để copy.');return;}await navigator.clipboard.writeText(payload);showSuccess('Đã copy toàn bộ SPC_ST.');}
async function copyCurrentSpcF(){const payload=state.batchAccounts.filter((x)=>x.ok&&x.spcF).map((x)=>x.spcF).join('\n')||state.currentSpcF||'';if(!payload){showError('Chưa có SPC_F để copy.');return;}await navigator.clipboard.writeText(payload);showSuccess('Đã copy toàn bộ SPC_F.');}
function buildUpdatedLoginSource(){const successItems=state.batchAccounts.filter((x)=>x.ok&&x.spcSt);if(successItems.length){return state.batchAccounts.map((item)=>{if(!item.ok||!item.spcSt)return item.source;if(/SPC_ST=[^|\s"]+/.test(item.source))return item.source.replace(/SPC_ST=[^|\s"]+/, 'SPC_ST='+item.spcSt);return item.source+'|SPC_ST='+item.spcSt;}).join('\n');}if(!state.currentSpcSt)throw new Error('Chưa có SPC_ST mới để cập nhật.');const source=String(state.loginSourceRaw||(els.loginInput?els.loginInput.value:'')||'').trim();if(!source)throw new Error('Chưa có chuỗi gốc để cập nhật.');if(/SPC_ST=[^|\s"]+/.test(source))return source.replace(/SPC_ST=[^|\s"]+/, 'SPC_ST='+state.currentSpcSt);return source+'|SPC_ST='+state.currentSpcSt;}
async function updateSpcStInSource(){try{const updated=buildUpdatedLoginSource();if(els.loginInput)els.loginInput.value=updated;await navigator.clipboard.writeText(updated);showSuccess('Đã cập nhật toàn bộ SPC_ST và copy.');}catch(error){showError(error.message||'Không thể cập nhật SPC_ST.');}}
function toggleAccordion(trigger,panel,isOpen){if(!trigger||!panel)return;trigger.setAttribute('aria-expanded',isOpen?'true':'false');panel.classList.toggle('hidden',!isOpen);panel.classList.toggle('is-open',isOpen);}
function handleCatalogClick(event){const copyButton=event.target.closest('[data-copy-code]');if(copyButton){navigator.clipboard.writeText(copyButton.getAttribute('data-copy-code')||'').then(()=>showSuccess('Đã copy mã voucher.'));return;}const saveButton=event.target.closest('[data-save-code]');if(saveButton){const code=saveButton.getAttribute('data-save-code')||'';saveVoucherByCode(code,code);return;}const toggleButton=event.target.closest('[data-detail-toggle]');if(toggleButton){const code=toggleButton.getAttribute('data-detail-toggle')||'';const box=document.querySelector('[data-detail-box="'+CSS.escape(code)+'"]');if(box)box.classList.toggle('hidden');}}
function bindEvents(){if(els.cookieToggle)els.cookieToggle.addEventListener('click',()=>{state.cookieOpen=!state.cookieOpen;toggleAccordion(els.cookieToggle,els.cookiePanel,state.cookieOpen);});if(els.linkToggle)els.linkToggle.addEventListener('click',()=>{state.linkOpen=!state.linkOpen;toggleAccordion(els.linkToggle,els.linkPanel,state.linkOpen);});if(els.tabVoucher)els.tabVoucher.addEventListener('click',()=>{state.activeTab='voucher';syncTabUi();});if(els.tabFreeship)els.tabFreeship.addEventListener('click',()=>{state.activeTab='freeship';syncTabUi();});if(els.refreshButton)els.refreshButton.addEventListener('click',loadVoucherCatalog);if(els.saveFixedButton)els.saveFixedButton.addEventListener('click',saveEveryVisibleVoucher);if(els.linkSubmitButton)els.linkSubmitButton.addEventListener('click',submitVoucherLink);if(els.linkInput)els.linkInput.addEventListener('keydown',(e)=>{if(e.key==='Enter')submitVoucherLink();});if(els.list)els.list.addEventListener('click',handleCatalogClick);if(els.loginButton)els.loginButton.addEventListener('click',loginByAccount);if(els.loginInput)els.loginInput.addEventListener('keydown',(e)=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey))loginByAccount();});if(els.qrButton)els.qrButton.addEventListener('click',startQrLogin);if(els.qrCancelButton)els.qrCancelButton.addEventListener('click',cancelQrLogin);if(els.copyCookieButton)els.copyCookieButton.addEventListener('click',copyCurrentSpcSt);if(els.copySpcFButton)els.copySpcFButton.addEventListener('click',copyCurrentSpcF);if(els.updateSpcStButton)els.updateSpcStButton.addEventListener('click',updateSpcStInSource);if(els.cookieInput)els.cookieInput.addEventListener('change',renderCatalog);}
bindEvents();syncSpcDisplay();toggleAccordion(els.cookieToggle,els.cookiePanel,true);toggleAccordion(els.linkToggle,els.linkPanel,false);loadVoucherCatalog();
